feat: Dockerfile for multi-staged builds.
code100x/muzer pull request #94
Opened 2024-09-13 21:11 UTC by geekyharsh05

This pr solves the issue: #91 

I have made changes to the following files:
- Added Dockerfile.prod
- Changed the exisiting Dockerfile.dev
- Refactored minute things.

**Without the multistage builds the size of the image was approx `1GB`, after implementing it the size reduces down to `187MB`.**

<img width="1182" alt="Screenshot 2024-09-14 at 1 37 53 AM" src="https://github.com/user-attachments/assets/4e05fc93-bf02-474e-bd7c-7694a0e214a0"> <br />

This is the local docker-compose results, everything works fine.

<img width="1182" alt="Screenshot 2024-09-14 at 1 37 43 AM" src="https://github.com/user-attachments/assets/6ced63f5-7cbd-441f-b269-f1fdcacf93d3">

I have tested every thing on my end.

**Can you Please review it and let me know if any adjustments are needed.**

2024-09-13 21:13 UTC, geekyharsh05 commented
@SujithThirumalaisamy Can you Please review it?

2024-09-14 07:51 UTC, geekyharsh05 commented
@SujithThirumalaisamy Should I make a scripts folder and write a shell file there and then use it in the Dockerfile file. This way it'll look more cleaner, What do you say?

2024-09-14 09:43 UTC, SujithThirumalaisamy commented
> @SujithThirumalaisamy Should I make a scripts folder and write a shell file there and then use it in the Dockerfile.
> 
> This way it'll look more cleaner, What do you say?

I think we are fine for now. Not necessary

2024-09-14 10:25 UTC, SujithThirumalaisamy commented on next-app/Dockerfile.dev
>  COPY prisma ./prisma
Move this to be happen after the install. use `--ignore-scripts` to ignore the scripts. And then do prisma generate manually. 

This will reinstall everytime you work on prisma. Yeah we wont do that much. But will be helpful

2024-09-14 10:28 UTC, SujithThirumalaisamy requested changes
Also please remove the lock file changes

2024-09-14 11:12 UTC, geekyharsh05 commented on next-app/Dockerfile.dev
>  COPY prisma ./prisma
Okay!

2024-09-14 11:30 UTC, SujithThirumalaisamy commented
I think the lock file got added in the last commit please remove it

2024-09-14 11:33 UTC, geekyharsh05 commented
@SujithThirumalaisamy Is it fine?

2024-09-14 11:35 UTC, SujithThirumalaisamy commented
You totally removed the lock. Just add the old one form the current `HEAD`

2024-09-14 11:42 UTC, geekyharsh05 commented
@SujithThirumalaisamy

2024-09-14 13:09 UTC, SujithThirumalaisamy commented
Thankyou sir. Great

2024-09-14 13:09 UTC, merged