Added Spaces  to muzer and resolved conflicts #84
code100x/muzer pull request #95
Opened 2024-09-14 07:41 UTC by Vishawdeep-Singh

What this PR fix or add ?
Ans-: I have added spaces or rooms to stream music so that one user can create many spaces.

https://github.com/user-attachments/assets/0da35e3f-71ef-433a-bf44-bce222d3a336

2024-09-14 08:09 UTC, Vishawdeep-Singh commented
#84 I resolved the conflicts and merge database migrations into two file

2024-09-14 09:00 UTC, Vishawdeep-Singh commented
@SujithThirumalaisamy

2024-09-14 09:44 UTC, SujithThirumalaisamy commented
Checking this

2024-09-14 10:08 UTC, Vishawdeep-Singh commented
> Checking this

Now it should pass all the checks , i updated the pnpm-lock.yaml file. Now lockfile is up to date.

2024-09-14 10:19 UTC, SujithThirumalaisamy reviewed
Great work. Please follow up sir

2024-09-14 10:19 UTC, SujithThirumalaisamy commented on next-app/prisma/schema.prisma
> +  startTime     DateTime    @default(now())
Do we really need start and End time?

2024-09-14 10:19 UTC, SujithThirumalaisamy commented on next-app/package.json
> +    "@nextui-org/react": "^2.4.6",
Should we use next-ui's skeleton? We already have shad-cn configured. They also provide the skeleton componenet

2024-09-14 10:19 UTC, SujithThirumalaisamy commented on next-app/package.json
> +    "framer-motion": "^11.5.4",
Hope this is related to next-ui. If we use shadcn we might remove this. Framer motion is a bit heavy thing

2024-09-14 10:19 UTC, SujithThirumalaisamy commented on next-app/tailwind.config.ts
> +    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
This may also improvise bugs in future because you are only adding the files from the theme. If we use other components out out theme directory in `next-ui` tailwind may not track it

2024-09-14 10:19 UTC, SujithThirumalaisamy commented
Also remove the lock file in the ws

2024-09-14 10:24 UTC, thepradipvc commented
Hey, if we are using API routes from the start, why are we only introducing actions and not continuing everything in API routes? It just makes things scattered all over the place.

2024-09-14 11:16 UTC, SujithThirumalaisamy commented
> Hey, if we are using API routes from the start, why are we only introducing actions and not continuing everything in API routes? It just makes things scattered all over the place.

Yeah makes sense

2024-09-14 11:16 UTC, SujithThirumalaisamy commented
@Vishawdeep-Singh Can we please stick to api calls. Make it as routes

2024-09-14 15:19 UTC, Vishawdeep-Singh commented
> @Vishawdeep-Singh Can we please stick to api calls. Make it as routes

sure done sir

2024-09-14 15:19 UTC, Vishawdeep-Singh commented on next-app/tailwind.config.ts
> +    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
removed next-ui entirely from code . And used shad cn

2024-09-14 15:21 UTC, Vishawdeep-Singh commented on next-app/prisma/schema.prisma
> +  startTime     DateTime    @default(now())
I thought maybe in future  , the spaces might say ,For many hours it had been live . But I removed it

2024-09-14 15:22 UTC, Vishawdeep-Singh commented on next-app/components/HomeView.tsx
> +"use client";
https://github.com/user-attachments/assets/e231d173-18db-4d88-9aef-41d3c5f6e37c

This is the homeview  /home . Where a user automatically redirected to after login . Here user can create and see spaces.

2024-09-14 15:23 UTC, Vishawdeep-Singh commented on next-app/components/HomeView.tsx
> +        toast.error("Error fetching spaces", {
Done

2024-09-14 15:25 UTC, Vishawdeep-Singh commented on next-app/app/creator/[creatorId]/[spaceId]/page.tsx
> +import OldStreamView from "@/components/OldStreamView";
I created entirely different /spaces/spaceId route . if you are using oldstreamview (NOT WEBSOCKET) . 
If you are using websocket I didnt touch the intial /creator/creatorId route.

2024-09-14 15:26 UTC, Vishawdeep-Singh commented
> Hey, if we are using API routes from the start, why are we only introducing actions and not continuing everything in API routes? It just makes things scattered all over the place.

Man i thought it was the better way to do fetches . But you are right . Should've done that

2024-09-14 15:31 UTC, Vishawdeep-Singh commented
@SujithThirumalaisamy Is there anything to change ?

2024-09-14 15:32 UTC, SujithThirumalaisamy commented
> @SujithThirumalaisamy Is there anything to change ?
> 
> 

Will check and update this

2024-09-14 20:46 UTC, SujithThirumalaisamy requested changes
Ideally I will merge this to a new branch and will create an issue to migrate this to WS

2024-09-14 20:46 UTC, SujithThirumalaisamy commented on next-app/app/creator/[creatorId]/[spaceId]/page.tsx
> +import OldStreamView from "@/components/OldStreamView";
yeah I got it. Just move it to `/spaces/[spaceId]`

2024-09-14 20:46 UTC, SujithThirumalaisamy commented on next-app/package.json
> +    "@radix-ui/react-progress": "^1.1.0",
You have this and the progress bar component added. Where are you using this?

2024-09-15 04:29 UTC, Vishawdeep-Singh commented on next-app/package.json
> +    "@radix-ui/react-progress": "^1.1.0",
I am very sorry for that .  I was just trying something new. Removed it 👍

2024-09-15 04:40 UTC, Vishawdeep-Singh commented on next-app/app/creator/[creatorId]/[spaceId]/page.tsx
> +import OldStreamView from "@/components/OldStreamView";
I am sorry i didn't get  what you mean ? You mean should i remove the /creator/[creatorId] and i already created /spaces/[spaceId] .

2024-09-15 06:43 UTC, SujithThirumalaisamy commented on next-app/app/creator/[creatorId]/[spaceId]/page.tsx
> +import OldStreamView from "@/components/OldStreamView";
Yeah its fine now.

2024-09-15 06:44 UTC, merged